on:
  pull_request_review:
    types: [submitted]

jobs:
  approve-staging-pr:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'production'
    steps:
      - uses: actions/checkout@v2
      - name: Fetch staging PR ID
        id: fetch_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo AUTOMATED_PR_TITLE="${{ github.event.pull_request.title }}" | sed "s/\[P\] //g" >> $GITHUB_ENV
          echo ${{env.AUTOMATED_PR_TITLE}}
          pr_id=$(gh pr list --search "${{env.AUTOMATED_PR_TITLE}} in:title" --json number --jq '.[0].number')
          echo "staging_pr_id=$pr_id" >> $GITHUB_OUTPUT

      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.CUSTOM_PAT }}
          script: |
            const result = await github.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{ steps.fetch_pr.outputs.staging_pr_id }},
            event: "APPROVE",
            body: `Approved by ${context.payload.review.user.login}`
            })
