name: "Auto-Approve Staging PR"
on:
  pull_request_review:
    types: [submitted]

jobs:
  approve-staging-pr:
    continue-on-error: true
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'production'
    steps:
      - uses: actions/checkout@v2
      - name: Fetch staging PR ID
        id: fetch_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo xoxoxoox
          echo ${{ github.event.pull_request.title }}
          AUTOMATED_PR_TITLE=$(echo "${{ github.event.pull_request.title }}" | sed "s/\[P\] /\[S\] /g")
          echo "ATUOMATED_PR_TITLE xxx"
          echo $AUTOMATED_PR_TITLE
          pr_id=$(gh pr list --search "$AUTOMATED_PR_TITLE in:title" --json number --jq '.[0].number')
          echo "staging_pr_id=$pr_id" >> $GITHUB_OUTPUT
          if [ -n "$pr_id" ]; then
            echo "pr_found=true" >> $GITHUB_OUTPUT
          else
            echo "pr_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Approve Staging PR
        if: steps.fetch_pr.outputs.pr_found == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_PAT }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ steps.fetch_pr.outputs.staging_pr_id }}/reviews \
            -d '{
              "event": "APPROVE",
              "body": "Approval by ${{ github.event.review.user.login }} automatically propagated from production Pull Request"
            }'
