on:
  pull_request:
    branches:
      - production

jobs:
  edit-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Edit PR title
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_PREFIX: "[P]"
        with:
          route: PATCH /repos/{owner}/{repo}/pulls/${{ github.event.pull_request.number }}
          title: "${{ env.PR_PREFIX }} ${{ github.event.pull_request.title }}"

  create-staging-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_PREFIX: "[S]"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create and merge new branch
        run: |
          git checkout staging
          git checkout -b "staging-${{ github.head_ref }}"
          git merge "origin/${{ github.head_ref }}"
          git push origin "staging-${{ github.head_ref }}"

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "staging-${{ github.head_ref }}"
          destination_branch: "staging"
          pr_title: "${{ env.PR_PREFIX }}${{ github.event.pull_request.title }}"
          pr_body: ${{ github.event.pull_request.body }}
          pr_label: "automated"
