on:
  pull_request:
    branches:
      - production

jobs:
  edit-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Edit PR title
        uses: octokit/request-action@v2.x
        with:
          route: PULLS/${{ github.event.pull_request.number }}
          method: PATCH
          body: |
            {
              "title": "[P] ${{ github.event.pull_request.title }}"
            }
          github_token: ${{ secrets.GITHUB_TOKEN }}

  create-staging-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create and merge new branch
        run: |
          git checkout staging
          git checkout -b staging-${{ github.head_ref }}
          git merge ${{ github.head_ref }}
          git push origin staging-${{ github.head_ref }}

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "staging-${{ github.head_ref }}"
          destination_branch: "staging"
          pr_title: "[S]${{ github.event.pull_request.title }}"
          pr_body: ${{ github.event.pull_request.body }}
          pr_label: "automated"
          github_token: ${{ secrets.GITHUB_TOKEN }}
